// Generated by https://quicktype.io

export interface Company {
  id: number
  name: string
  carrier_code: string
}

export interface Role {
  id: number
  name: string
}

export interface Users {
  id: number
  name: string
  email: string
  email_verified_at: string
  uuid_fb: null | string
  active: boolean
  remember_token: null
  created_at: string
  updated_at: string
  deleted_at: null
  role: Role
  company: Company
}

export interface UsersResponse {
  data: Users[]
}
