import { globalApi } from '../../../store/globalApi'
import mainApi from '../../../utils/AxiosService'

// Generated by https://quicktype.io

export type Statuses = {
  id: number
  name: string
  code: string
  terminal: boolean
}

export type keyStatus = keyof Statuses

const apiTrackingTags = globalApi.enhanceEndpoints({
  addTagTypes: []
})

export const trackingApiSlice = apiTrackingTags.injectEndpoints({
  endpoints: (builder) => ({
    getStatuses: builder.query<Statuses[], void>({
      queryFn: async () => {
        try {
          const { data } = await mainApi('statuses')
          return { data }
        } catch (error: any) {
          return {
            error
          }
        }
      }
    })
  })
})

export const { useGetStatusesQuery } = trackingApiSlice
