// Generated by https://quicktype.io
export interface Company {
  id: number
  name: string
  carrier_code: string
}

export interface Destination {
  name: string
  email: string
  phone: string
  addressDestination?: string
  latitude: string
  longitude: string
  country: string
  notes: string
  addressOrigin?: string
}

export interface Ecommerce {
  id: number
  name: string
}

export interface Label {
  pdf: string
}

export interface Status {
  id: number
  name: string
  code: string
  terminal: boolean
}
export interface Deliveries {
  id: number
  imported_id: string
  tracking_number: string
  label: Label
  origin: Destination
  destination: Destination
  created_at: string
  updated_at: string
  status: Status
  company: Company
  ecommerce: Ecommerce
}
export interface DeliveriesResponse {
  count: number
  data: Deliveries[]
}
