// Generated by https://quicktype.io

export interface Destination {
  level1: string
  level2: string
  level3: string
  level4: null
}

export interface Label {
  pdf: string
  zpl: string
}

export interface Origin {}

export interface Status {
  id: number
  name: string
  code: string
  terminal: boolean
}

export interface DeliveriesResponse {
  id: number
  imported_id: string
  tracking_number: string
  label: Label
  origin: Origin
  destination: Destination
  company_id: number
  ecommerce_id: number
  status: Status
}
