// Generated by https://quicktype.io

export interface Company {
  id: number
  name: string
  carrier_code: string
}
export interface Companies {
  count: number
  data: Company[]
}
export interface CompaniesResponse {
  companies: Companies
}
