// Generated by https://quicktype.io

export interface Label {
  pdf: string
}

export interface Destination {
  name: string
  email: string
  phone: string
  addressDestination?: string
  latitude: string
  longitude: string
  country: string
  notes: string
  addressOrigin?: string
}
export interface SummaryToDeliveriesResponse {
  status_id: number
  status_name: string
  status_code: string
  status_terminal: boolean
  company_id: number
  company_name: string
  company_carrier_code: string
  ecommerce_id: number
  ecommerce_name: string
  id: number
  imported_id: string
  tracking_number: string
  label: Label
  origin: Destination
  destination: Destination
  created_at: string
  updated_at: string
}
