// Generated by https://quicktype.io

export interface Destination {
  name: string
  email: string
  phone: string
  addressDestination?: string
  latitude: string
  longitude: string
  country: string
  notes: string
  addressOrigin?: string
}

export interface SummaryToDeliveriesResponse {
  id: number
  imported_id: string
  tracking_number: string
  label: string
  status: number
  origin: Destination
  destination: Destination
  company_id: number
  ecommerce_id: number
  created_at: string
  updated_at: string
  deleted_at: string
}
