// Generated by https://quicktype.io
export interface Evidence {
  comment?: string
  name?: string
  rut?: string
}

export interface PayloadSummaries {
  summaries_ids: number[]
  status_id?: number
  user_id?: number
  evidence?: Evidence
}
