// Generated by https://quicktype.io

export interface Carrier {
  id: number
  name: string
  code: string
}

export interface Summaries {
  id: number
  evidence: string
  truck_id: number
  created_at: string
  updated_at: string
  deleted_at: null
  carrier: Carrier
}

export interface SummariesResponse {
  data: Summaries[]
  total: number
  page: number
  lastpage: number
}

export interface Pagination {
  page: number
  limit: number
}
