// Generated by https://quicktype.io
export interface Company {
  id: number
  name: string
  carrier_code: string
}

export interface Summary {
  id: number
  evidence: string[]
  created_at: string
  updated_at: string
  deleted_at: null
  company: Company
  CountDeliveries: number
}

export interface SummariesResponse {
  summaries: Summary[]
  total: number
  page: number
  lastpage: number
}
